### ISSUE TITLE
Get array element dynamically in antlers via `{{ array[key] }}` syntax?

### ISSUE THREAD

**Issue by jesseleite** [statamic/ideas#191]
Would be nice to get an array element dynamically in antlers using square bracket `{{ array[key] }}` syntax.

```html
---
feature_class:
  - red
  - orange
  - yellow
---

{{ features }}
    <div class="feature {{ view:feature_class[index] }}">...</div>
{{ /features }}
```

I've tried `array.{key}` and `array.{{key}}`, but doesn't work atm in v3.  That said, the square bracket syntax is fairly conventional in other languages.

**Comment by morhi** [comment]
I'd love that! I have a lot of struggles because of this when creating forms, where I need to access the `old` variables inside a loop while not knowning the actual name of the key.

Actually, I just created a little change which makes this syntax available: https://github.com/morhi/statamic-cms/commit/e0918eec9a62d5dd2f7b28c957c1f26c464b8d64

**Comment by jackmcdade** [comment]
Merged!
