### ISSUE TITLE
FR: Add group fieldtype

### ISSUE THREAD

**Issue by goellner** [statamic/ideas#210]
As discussed in Discord (https://discordapp.com/channels/489818810157891584/489825364902805505/703140537598869504) a while ago, it would be super helpful to have a group fieldtype to reuse the same field and don't have to prefix every sub field. 

Ben built an addon for v2, which does exactly that: https://statamic.com/marketplace/addons/group

**Comment by JonKaric** [comment]
I'm currently building a site where a group fieldtype would be useful. There is currently no workaround that is clean, either your data is dirty, your templating is dirty, or both. The nearest thing is the grid fieldtype, but that saves data as an array - even if you only have 1. 

A group field type makes sense especially in the context of fieldsets. Would be nice to just import a fieldset into a group and have this as the output:

```yaml
lg: 
  image:
  container:
```

Instead of bringing in individual fields and prefixing:
```yaml
lg_image: 
lg_container:
```

**Comment by jasonvarga** [comment]
Implemented in statamic/cms#8836
