### ISSUE TITLE
Yields and sections to be template engine agnostic

### ISSUE THREAD

**Issue by johncarter-** [statamic/ideas#231]
It would be just lovely if the `{{ section }}` tag would push to a Blade `@yield()`.

### Example

Using a blade layout `layout.blade.php` with a `@yield('bananas')` it would be great if I could use an antlers template with:

```
{{# show.antlers.html #}}

{{ section:bananas }}
peanuts
{{ /section:bananas }}
```

**Comment by jasonvarga** [comment]
Fun tip, since the template is already being pushed into a variable, you can just render it.

```
{!! $template_content !!}
```

Or, if your layout is going to potentially handle both Antlers *and* Blade templates, you can still `yield` for Blade, and fall back to the variable for Antlers. Wrap it in an `HtmlString` object so the HTML doesn't get escaped.

```
@yield('bananas', new \Illuminate\Support\HtmlString($template_content))
```

In your Antlers templates, you don't need the section tag.

I'll leave this open though, since it's fairly counter intuitive. Using the section tag like you want makes a lot of sense for people coming from Blade.

**Comment by johncarter-** [comment]
Sorry for being thick Jason, but I'm not quite following. For the record I am using Antlers and Blade.

I want to push a script / style html tag from an Antlers template _into_ a Blade layout.

This is what I have got so far:

**default.antlers.html**
```
<p>Before bananas</p>
{{ section:bananas }}
<div>Peanuts</div>
{{ /section:bananas }}
<p>After bananas</p>
```


**layout.blade.php** - not working

```
<html>
<head>
  @yield('bananas')
</head>
<body>
  @isset($template_content)
  {!! $template_content !!}
  @endisset
</body>
</html>
```

**layout.antlers.html** - works
```
<html>

<head>
  {{ yield:bananas }}
</head>

<body>
  {{ template_content }}
</body>

</html>
```

**Comment by jasonvarga** [comment]
Alright sorry, what I was showing was only for the injecting the entire template (`template_content`) into the layout.

If you wanna push just parts of it, then you'll have to wait for the feature to be implemented.

**Comment by duncanmcclean** [comment]
Closing since this was implemented in https://github.com/statamic/cms/pull/5056.
