### ISSUE TITLE
Auto-update slug when localizing a page

### ISSUE THREAD

**Issue by remiduval** [statamic/ideas#334]
Use case:
1/ I create an 'About' page (`/en/about`)
2/ I create its French localization, title defaults to 'About', I change it to 'A propos'
3/ I publish it. The URL is `/fr/about` when I'd probably want `/fr/a-propos`

The slug only auto-update during the creation of a page, which is probably a good thing to avoid 404s when changing the title in the future.
But I feel like it should also auto-update when creating a localization.
Or offer a button to update the slug when changing the title.

**Comment by PhilJ** [comment]
This would be highly anticipated feature from our perspective - and our clients ❤️  Both suggested solutions (auto-creation or creation by button press) would be fine from my perspective.

atm the editor's UX of slug creation in multi site is not very good, since slugs for second language sites have to be created manually. This is usually overseen by editors and a challenge to create manually.
