### ISSUE TITLE
Show filename, path, and extension when renaming an asset

### ISSUE THREAD

**Issue by wm-simon** [statamic/ideas#337]
If you rename an assets, there should be shown the current filename, which you want to edit, like in Statamic v2. The input field is empty now.

**Comment by j3ll3yfi5h** [comment]
> If you rename an assets, there should be shown the current filename, which you want to edit, like in Statamic v2. The input field is empty now.

Yes, this would still be nice!

**Comment by jasonvarga** [comment]
The "filename" label in the asset editor pointed out by Phil has been renamed to "path" in 3.3 via statamic/cms#7303.

The placeholder for field in the the rename action modal will show the filename in 3.4 via statamic/cms#7261.

**Comment by wturrell** [comment]
It's *really* annoying only having the name as a placeholder rather than a value if you want to modify it rather than wipe it completely (surely most use cases): as a placeholder you can't edit the name, and as soon as you start typing the old one disappears. Worse, in Assets list view, it's impossible to select the name with the mouse to copy and paste it.  

Instead currently you have to edit the asset, copy the name from the top left, click Rename, then paste it in, whilst remembering to remove the file extension from the end otherwise you end up with ``.pdf.pdf`` (see philsturgeon's earlier comment)
