### ISSUE TITLE
"Quick Start" in the docs

### ISSUE THREAD

**Issue by rosswintle** [statamic/ideas#36]
Yay! Congrats on v3 public beta, and sorry I've been out of the loop for a while.

I've been looking through the v3 docs on statamic.dev and - with my "I'm coming from another CMS" hat on, I feel like there's a lot of complicated, heavy, technical stuff to get through (Core concepts, templating/front end) before I actually find out how to use Statamic.

This is very much developer documentation, not user documentation.

This may be very deliberate. And it may be that you have a plan for user docs. And it may be that the "Screencasts" page which currently 404's will cater for this.

But I also wonder if another "path" to reading the docs should be made, one that enables people to get up and running more quickly so that they can check out Statamic without having to invest a heap of time in reading so much.

What do you think?

**Comment by jackmcdade** [comment]
Absolutely. I haven't done those pages yet because i wanted to the get the core "reference" pages done first. I was thinking they'd be the **tutorial** section, which right now is greyed out and at the bottom, but I would likely move them all the way up to the top, and then feature them prominently on the homepage once we're out of beta.

How does that feel to you?

**Comment by rosswintle** [comment]
You're 714 steps ahead of us all as always! Sounds great. 👍
