### ISSUE TITLE
Don’t allow using CP updater in Production

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/ideas#377]
I've seen a few people try to update their sites in production and when it fails, the site goes down.

It might be a good idea to not let people preform Statamic Updates in the CP if the site is in a production environment.

**Comment by jelleroorda** [comment]
Personally I think that this would not be a good change, since some less experienced developers might go and change the app environment to local quickly to “update the CP”, which will then dump their credentials if the update bricks their site. I am however a fan of displaying a warning message (maybe even a confirmation pop-up) along the lines of: “Updating the control panel might lead to a broken site, so we recommend doing this on your development environment only. Are you really sure you wish to proceed?”

**Comment by MeMattStone** [comment]
I'm surprised more people haven't requested this feature. I think having the ability to disable updating either through a method in code or via an environment variable that can be added to a particular environment's `.env` file  e.g. `STATAMIC_DISABLE_CP_UPDATES=true` would be incredibly useful, especially where non-developers may have admin access to a production site. 

WordPress (and a few other CMS) already have the ability to disable admin panel updates programatically or through their respective configurations.

**Comment by jesseleite** [comment]
Just noting that we already support permissions around viewing and performing updates, should you not want your users doing certain things like this in the CP... 

![CleanShot 2022-10-11 at 16 55 03](https://user-images.githubusercontent.com/5187394/195196447-741a6899-394f-4f4f-969b-fc1c62ab3225.png)

**Comment by MeMattStone** [comment]
It's more for super admins that we want to block this ability, having the ability to globally block updates via the admin UI is preferable

**Comment by duncanmcclean** [comment]
Closing as the ability to run updates in the Control Panel was removed completely in v4.
