### ISSUE TITLE
Taxonomy navigation current

### ISSUE THREAD

**Issue by lightbringer93** [statamic/ideas#404]
I have a taxonomy navigation and I want to mark the current taxonomy. I tried to use `is_current` but it does not work? Is there another attribute that I could use? 

```
{{ taxonomy:publication_type collection="publications" }}
    <a class="block border-b border-gray-300 pt-4 pb-2 hover:text-primary-500 focus:text-primary-500 duration-200 ease-in-out{{ is_current ?= ' text-primary-500 border-primary-300' }}"
   href="{{ url }}">
    {{ menu_text }}
    </a>
{{ /taxonomy:publication_type }}
```

**Comment by jackmcdade** [comment]
You use URLs segments and slugs. 

Something like this:

```
{{ if segment_3 === slug }} // do the thing {{ /if }}
```

Closing as this isn't quite an idea or feature request. :)

**Comment by lightbringer93** [comment]
Many thanks that worked!

**Comment by wesort** [comment]
Feature request for `is_current` variable on taxonomies.

`{{ if segment_3 === slug }} ` works if you're working with the taxonomy on its natural URLs, but not elsewhere. For example, in a navigation I'm working on, I want to highlight the current entry's second level nav item based on it's `type` (taxonomy).

```
{{ taxonomy:type }}
  <li>
    <a
      href="/work{{ url }}"
      class="{{ if segment_3 === slug }}text-red-500 {{ /if }}"
    >{{ title }}</a>
  </li>
{{ /taxonomy:type }}
```

Happy to use a workaround.

**Comment by jasonvarga** [comment]
You can use the `page` variable to reference the "thing" for the current page.

If you're on an entry's url (like `/blog/post`), you can do `{{ page:type }}` to get the `post` entry's `type`. Use that in your conditional. 

`{{ if slug == page:type|raw }}`
`slug` in the loop being the term's slug.
`page:type|raw`, being the slug of the entry's `type`. assuming you're using a terms field with `max_items: 1`. Gotta use the `raw` modifier because you want the slug, not the Term object itself.
