### ISSUE TITLE
Temporary Variables in Antlers

### ISSUE THREAD

**Issue by steveooo1** [statamic/ideas#41]
It would be great if there is a Twig and Blade like feature of temporarily variables. Surely, you should abstract most logic but those variables like Twigs `{% set fullName = firstName ~ ' ' ~ lastName %}` is very useful. Also the support for tags inside those declarations would be neat. `screamName = name|upper`

So it would be great if this get's added!

**Comment by steveooo1** [comment]
Ok, but no clue how to do this with view models...

**Comment by jackmcdade** [comment]
Did you check out the link in the docs? https://statamic.dev/view-models

**Comment by steveooo1** [comment]
Yeah, but now idea how this can be used for being able to define variables inside Antlers via some kind of `foo = bar` syntax...

**Comment by cherrykoda** [comment]
Looking forward to using blade in v3 in large part because of the lack of template variables support in Antlers. +1 for this request.

**Comment by piljac1** [comment]
I'm actually starting to regret my decision to choose the "recommended" way (Antlers). I'm also thinking of switching to Blade like @cherrykoda because of the lack of Antlers basic features (like setting a variable in this current case). I know creating/managing a templating requires a lot of effort, so I'm having trouble to understand why they went that way instead of extending a robust and versatile templating engine in Blade... I admire what the Statamic team has done with this product, but I just can't wrap my head around this particular decision.

And to answer to the proposed view model solution, it can solve some issues, but let's say for whatever reason we need to increment/decrement a variable based on some dynamic condition in a loop, we just can't.

**Comment by damcclean** [comment]
For some background: Antlers was built before things like Blade or Twig were built/stable.

Antlers has just evolved since v1 and has stayed the default templating language to feel familiar to existing Statamic developers.

**Comment by piljac1** [comment]
@damcclean  I guess that makes some sense. However, (correct me if I'm wrong) one of the main appeal of Statamic is that it is built with Laravel. So Laravel developers, like myself, choose Statamic because of the familiarity with the framework (collections, routing, overall MVC environment, etc.) and the beautiful UI and customer UX. That being said, it would be great if we could benefit from a stack decision (like Laravel Jetstream) that is supported in the core: would you like an Antlers setup or a Blade setup? I know you can always choose Blade over Antlers, but when I'm talking about a stack decision, I imply the Blade option would be extended to support similar logic found in Antlers (collections, recursive nav, etc.).

I understand old school Statamic developpers might be more familiar with Antlers, but I myself found the learning curve steep (and in the end, unsatisfying) because of two major things:

* Lack of documentation examples
* Lack of basic features (I spent a good amount of time trying to find out how to do certain Blade/PHP equivalent things in Antlers)

Would what I suggest (two different stacks) would be viable/maintainable? I doubt it very much since Statamic's team only consist of 3 full-time individuals, but I feel like it would be a MUCH appreciated feature by the Laravel community.

**Comment by jackmcdade** [comment]
Up until just one month ago with v3's launch – we only supported Antlers. That's 8 years of Antlers. To dump it in favor of Blade is to would break backwards compatibility and alienate tens of thousands of Statamic users who know and understand Antlers for those people who are just coming to Statamic because of Laravel. If we had to pick one or the other, we'd pick Antlers if only for that reason.

That being said, we definitely plan to make Blade more of a "first party" solution. We wanted to have it done for v3 launch, but decided since it's a **new** feature, we could launch without it. We simply need more time, that's all. Hang in there!

**Comment by piljac1** [comment]
@jackmcdade That's great news! By the way, I never said you guys should dump Antlers for Blade. I understand that the V1-V2 community is familiar with it and that it would have created an uproar if you would have made a total switch to Blade for V3 (a bit like when Wordpress switched from their classic editor to Gutenberg haha). I just felt like it would be nice to "feel" more of the Laravel environment by benefiting from the power of (the Force) Blade and Statamic related components/syntax.

Keep up the good work!

(By the way, do you have an ETA for that "first party" Blade solution?)

**Comment by jonassiewertsen** [comment]
This should be solved with the new Antlers Engine in 3.3

https://github.com/statamic/cms/pull/4257

Search for: `Creating Variables`
