### ISSUE TITLE
Ability to hook into password rules

### ISSUE THREAD

**Issue by edalzell** [statamic/ideas#422]
Recently saw this cool package: https://github.com/valorin/pwned-validator/.

Would be great if there was a way to add rules to the password validation, so folks could add this, if they wanted. Or other rules (complex password requirements, etc).

**Comment by rrelmy** [comment]
This would be really helpful for projects with minimal password requirements

**Comment by duncanmcclean** [comment]
Not sure this really fixes the problem but maybe Statamic could hook into new functionality from this PR.  laravel/framework #36960. Only issue is that it's Laravel 8 onwards 😂

**Comment by rrelmy** [comment]
I need at least some basic requirements on passwords because of a goverment project and am be willing to create a PR with a basic implementation for it.

My idea would be to make the current password validations (`required|confirmed`) configurable inside `config/statamic/users.php` configuration.

Would such a PR be welcome?

**Comment by jasonvarga** [comment]
Yup.

**Comment by rrelmy** [comment]
I made a [pull-request](https://github.com/statamic/cms/pull/3732) with a minimal proposal how to add additional validation rules.
