### ISSUE TITLE
PHP way to use Statamic tags and modifiers

### ISSUE THREAD

**Issue by felixstoessel** [statamic/ideas#433]
For an agnostic approach, it would be great to call and use Statamic tags and modifiers directly via PHP. This also would be needed if Statamic ever adds features to have a full Blade replacement for Antlers.

Besides Statamic tags and modifiers, are there other things I miss? Maybe things like @yield or some template inheritance logic.

**Comment by jasonvarga** [comment]
Pretty vague request. Since Antlers is written in PHP, naturally everything is already doable in PHP in some way.

Here's a way to use [tags](https://github.com/statamic/cms/pull/2724/files#diff-7827dcf8c28ba9d97397f03b4ca75c132540f5c377e253fbc47ef064a373ce73R27-R47). This is what's involved in setting up the tag class, passing in the context etc. This is only necessary if the tag you're trying to use is very coupled to Antlers. 
For tags that are really just wrappers for other things, you can open up the class and see how it's being used. e.g. the [mix tag](https://github.com/statamic/cms/blob/3.0/src/Tags/Mix.php) is just using the global mix function.

Modifiers, you can follow what's explained here: https://statamic.dev/template-engines#modifiers-blade

For yield - that's a very template engine specific thing. Of course, Blade already has it's own version, which is what the Antlers one was inspired by.

If you need something else, feel free to ask, but please be specific.
