### ISSUE TITLE
[FR] Fallback for collection taxonomy template files if none exist

### ISSUE THREAD

**Issue by austriker27** [statamic/ideas#511]
# The idea
I propose that for Collection Taxonomy Template files there be a fallback if they don't exist. 

(Or perhaps an error should be thrown)

# Example & Solution
For example, a collection of `escape_artist_dogs` has a mounted taxonomy of `types`

So if these files don't exist:
```
views/escape_artist_dogs/types/show.antlers.html
views/escape_artist_dogs/types/index.antlers.html
```

Then statamic defaults back to the Global Taxonomy template file:
```
views/types/show.antlers.html
views/types/index.antlers.html
```

Thanks!

**Comment by duncanmcclean** [comment]
Out of curiosity, what happens currently?

**Comment by austriker27** [comment]
> Out of curiosity, what happens currently?

It hits the 404 page. Although I haven't tested it robustly. It was hitting the 404 page for "new" tags but only for new tags.

**Comment by duncanmcclean** [comment]
Ah gotcha, okay!

**Comment by jasonvarga** [comment]
The whole point is that the existence of the view is what controls whether there's a page. Otherwise we're left with the problem that what if you _don't_ want that page?

What you could do is use a partial, like the cool writings starter kit does:

https://github.com/statamic/starter-kit-cool-writings/tree/master/resources/views/articles/topics

On the collection-specific views, it just includes the non-collection ones.
