### ISSUE TITLE
Meili Search

### ISSUE THREAD

**Issue by goellner** [statamic/ideas#540]
Support for the open source Algolia alternative would be awesome.

Infos about it can be found here: https://github.com/meilisearch/meilisearch

**Comment by tao** [comment]
I wrote a [MeiliSearch driver](https://github.com/elvenstar/statamic-meilisearch) for Statamic, it works fine but it needs some more testing... just install it and use `meilisearch` instead of `algolia` in the config. It's not that complex to write a custom search driver.

I also wrote one for [Typesense](https://github.com/elvenstar/statamic-typesense) too but that's a bit more complex and ran into some bugs that make it unusable for production at the moment (but the devs said they'd work on it in the next few weeks).

While I was building this I found MeiliSearch is still relatively new and changing things, they are rebuilding the search engine core at the moment and there are some strange bugs I encountered, and the server crashed a few times. If you're doing something simple then it shouldn't be a problem... but I found (on this project) a lot of my markdown content on Statamic is more than 1000 words and MeiliSearch has a limit on that amount. I'm still looking for an elegant solution around that issue though.

So I wouldn't recommend including it in the Statamic CMS until it's more stable... it's at v0.2 now and will probably change more as they upgrade the core engine 🚀

It would be great if you want to test it and let me know if you find any bugs, it's my first composer package but I'll be working on them more as I get ready to launch my project in the next few weeks.

**Comment by jonassiewertsen** [comment]
That could be a great addon for the marketplace @tao 👌

**Comment by duncanmcclean** [comment]
Drivers for [Meilisearch](https://github.com/statamic-rad-pack/meilisearch) & [Typesense](https://github.com/statamic-rad-pack/typesense) are both available as addons, maintained by The Rad Pack. 

Closing as we're not looking at integrating any other drivers into Core at this time.
