### ISSUE TITLE
FR: CP configurable routes

### ISSUE THREAD

**Issue by edalzell** [statamic/ideas#71]
Would be super nice if Statamic routes were editable from the CP, instead of the settings files. I can see the situation where an end user would want to create a route that points to a template.

Apologies if this should be in `ideas`, never sure where these should go.

**Comment by jackmcdade** [comment]
Moved it to ideas because being in `cms` means we're planning to do it (vs a request). Don't want to keep a couple hundred open issues just for maybe someday.

**Comment by jasonvarga** [comment]
I don't really see the use case for a client-editable route. When you say "I can see the situation where ..." does that mean you've run into the need for it? Or you're just thinking hypothetically?

It really just sounds like a page to me.

In v2, yeah, you could edit the route in the CP, but that was just because it was editable as YAML. I don't think a client should be editing routes.

**Comment by edalzell** [comment]
For my site, I was actually switching from a page TO a route. Don't need it to be editable so wanted to aim it at an existing template without any of the "overhead" of making a page.

Perhaps I'm thinking wrong. Close away if it doesn't fit...

**Comment by jackmcdade** [comment]
Totally doing it right, just don't need to have those routes in the CP is all.
