### ISSUE TITLE
Remove email enumeration by serving generic messages in password reset

### ISSUE THREAD

**Issue by mirko-kienle** [statamic/ideas#752]
Hi, we've just finished building our first Statamic site for a client. The client has now had a security assessment run by an external infosec firm and one of their findings was the following:

> **Risk**: Moderate

> **CVSS3 Base Score**: 5.3 (CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N)

> **Category**: Information Leakage

> **Description**: User enumeration is when an attacker can determine if a username presented to the application is valid or not, due to the message returned from the server in response to authentication or password reset type of facility. This would allow the attacker to gain a list of valid usernames which could then be utilised in a brute-force attack or targeted phishing.

> **Details**: During the assessment a method of username enumeration was identified. Using the forgotten password function, the system would identify if the account entered was valid upon submission responding to the user with a non- generic message. If the account provided was valid then the system would respond that the email had been successfully sent; if the account was not valid then the user would receive a notification that a user could not be found with an email address. Given that no generic message is provided when the function is used, and that during the testing no rate limiting was identified for this; a malicious user can automate these requests to identify a list of valid usernames.

<img width="224" alt="Screenshot 2022-02-09 at 10 43 52" src="https://user-images.githubusercontent.com/39773181/153357130-12c767f5-7258-471b-a13e-c849fb24b6b9.png">

<img width="272" alt="Screenshot 2022-02-09 at 10 43 57" src="https://user-images.githubusercontent.com/39773181/153357154-111aef69-0e5a-4603-92bd-3017c58e749e.png">

> **Recommendations**: It is recommended that the server is reconfigured to respond to forgotten password requests with the same generic messages, therefore not providing any indication if a valid username was used.

This concerns the password reset functionality at `/cp/auth/password/reset`.

It is a clear attack vector even if the possible uses are limited. Best practice would seem to be serving generic messages instead of providing feedback on the (in)validity of submitted email addresses. This would remove the possibility of potential attackers using the functionality to scrape valid email addresses from the password reset form.

**Comment by jackmcdade** [comment]
To be perfectly honest, I don't see this as a realistic security issue at all. First, the location of your control panel should be renamed for obscurity. In that scenario, no one should know what that URL is. Or better yet, you could/should a staging server to work on, push changes to production, and not even enable the control panel at all in production.

If we provide the same generic password message no matter the scenario (e.g. successful vs throttled vs invalid token vs wrong email), the user has a degraded experience because they don't know what they did wrong. They could wait an hour for an email that's never coming, and most companies don't have full time staff to provide support for their users, leaving frustrated folks in smb companies in the dark. 

If this "vector" is an issue for your client, I suggest implementing one of the aforementioned measures to satisfy the scenario. Thanks!
