### ISSUE TITLE
Glide caching: I don't get it

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/ideas#795]
The glide cache variable confuses me and I don't see away of taking advantage of remote glide cache storage when this variable is set to false. I may be totally misunderstanding something here but allow me to try and explain.

## I don't think glide cache config variable is what it says

When I set ` image_manipulation.cache = true` Glide cache files are created under: public/img

But this confuses me because when I set ` image_manipulation.cache = false`, Glide is still caching files, but under: storage/framework/cache/glide

So ` image_manipulation.cache` isn't toggling Glide caching. Caching is always happening anyway. What this variable does is:
- image_manipulation.cache = false: Manipulate each image only when the browser requests an img src.
- image_manipulation.cache = true: Manipulate all images before serving the page.

For me a better name for this variable is image_manipulation.**prerender**

## I would like cache files stored remotely regardless of the above setting

It seems that we can only take advantage of remote glide caching when prerendering images. The Spatie reponsive image package recommends not using Statamic's glide caching, and I can see why. If a page has 50 images, and each image needs multiple sizes / jpeg fallbacks, then you could be attempting to prerender hundreds of images, which will timeout most servers. For this reason I keep the glide cache setting to false and so I cannot take advantage of remote glide caching.

But as explained above, glide images are being cached anyway. It would be nice if images stored by default under storage/framework/cache/glide could be sent to remote storage such as S3 or digitalocean. Perhaps they can??

Thanks for reading.

**Comment by jasonvarga** [comment]
The naming isn't great, but we stuck with it because changing it would be a breaking change.

I'll try to explain the differences.

### Default mode / Cache disabled

The default mode, which is the "cache disabled", will generate the images when you visit a Statamic URL.
When the user visits the URL, Statamic will generate the image using Glide if it doesn't already exist, and serve it.

Every time a user visits this URL, it's a full PHP request, and does a fair bit of work (relatively speaking) to check if the image exists, etc.

There's technically still a cache in the storage directory as you've pointed out, but its just somewhere out of the way.

### Cache enabled

You aren't really enabling the cache, you're really just pointing it to a public location.
The Glide images are "prerendered" as you've pointed out, and we do that so that we're able to point to a real static image URL. When the user visits those URLs, they are literally just images. There's no PHP request at all. It's just the server, it's fast.

### Why you can't have both

Ask yourself why you want your cached images on a remote filesystem? It's so you can serve them through a CDN for speed.

In that case, they'll need to exist at a static URL.

You only get the speed benefit if the next time you request the image, it's from S3 directly. If you have to hit your Statamic site, and have it read the file from S3 behind the scenes, that would be even slower.

If you're concerned about those initial requests taking a long time and running out of memory, you can define presets. Whenever you upload a new asset, the presets will be generated then, and won't need to be generated when you load a view. https://statamic.dev/image-manipulation#presets
