### ISSUE TITLE
Bard Minimal Mode

### ISSUE THREAD

**Issue by lakkes-ra** [statamic/ideas#893]
We often use bard as a wysiwyg editor for smaller text parts that sometimes even are just some words. As bard is a little »bulky« for one-liner, we added some custom css to make the bard field just as small as a normal text field. 

Maybe it's an idea to add a option to have smaller, minimal bard?

**Comment by lakkes-ra** [comment]
Thank you for the info, looking forward to TipTap 2! 

Since you already posted the idea, I'll close this one again.

**Comment by jacksleight** [comment]
Well, that one is closed, so you could leave this open 😊 .

**Comment by jacksleight** [comment]
Turns out it's very possible with Tiptap 2:

https://user-images.githubusercontent.com/126740/198254414-a4a8353d-9a80-421b-b8f3-9706afc88320.mp4

@jackmcdade Any interest in having this in core (for 3.4+)? Tiptap 2 makes the implementation pretty simple! Although I'm sure there are a bunch of things I haven't thought of. Some features would certainly need to be switched off in this mode.

**Comment by jackmcdade** [comment]
I don't see why not! That could be really nice to have.

**Comment by jacksleight** [comment]
Awesome, I'll do a PR. 👍

**Comment by jackmcdade** [comment]
Added in https://github.com/statamic/cms/pull/6973.
