### ISSUE TITLE
Resize Images on Upload

### ISSUE THREAD

**Issue by sjclark** [statamic/ideas#937]
😄 **It would be great if images could be resized to a definable maximum dimensions on upload.** I would suggest adding a new section to `config/statamic/assets.php` right underneath `Image Manipulation Presets`. If (for many people) resizing actions are already being run on upload, I figure its not too much more work to also set a maximum pixel dimension size here as well?

Alternatively the `keep_original` flag [previously suggested](https://github.com/statamic/v2-hub/issues/1528) being added to the presets could also work well?

I ended up writing a **local** applescript that takes all images, resizes them to maximum dimensions, runs them through imageoptim. But it fills up repo's (due to the duplication) and is obviously a bit clunky for something that's built into many CMS's (Wordpress, CraftCMS, Drupal, Webflow, Squarespace etc - aware Statamic is smaller than these). 

Seems this has been an issue since v2 days, and was suggested that an Idea be posted here;
https://github.com/statamic/v2-hub/issues/1528#issuecomment-1112915100

**Comment by jesseleite** [comment]
> It would be great if images could be resized to a definable maximum dimensions on upload

This is coming in 3.4 https://github.com/statamic/cms/pull/6040 🤘

![CleanShot 2023-01-16 at 14 08 40](https://user-images.githubusercontent.com/5187394/212750757-907a3f44-990d-4c29-a822-532180377888.png)

> Alternatively the `keep_original` flag previously suggested being added to the presets could also work well

With this new implementation, a `keep_original` flag is not needed. If you want to keep your original unmodified image, then instead of processing uploads directly, you can select which preset manipulations(s) you wish to warm post-upload.
