### ISSUE TITLE
Hide empty computed fields

### ISSUE THREAD

**Issue by aerni** [statamic/ideas#949]
I've got this computed field that shows all articles of an author. It looks a little lost if there are no articles:

<img width="937" alt="Bildschirmfoto 2023-02-08 um 11 08 13" src="https://user-images.githubusercontent.com/23167701/217585185-aae4c54e-c9b8-4bc6-897a-9554aae0c747.png">

Maybe we should hide computed fields if they have no value. Not sure about the best approach here.

**Comment by jasonvarga** [comment]
This is more of an issue about the entries fieldtype's style when in read only mode.

The same thing happens if you have an entries field set to read only and it has nothing selected.

If your computed field was a text fieldtype, it would be a read only text box, which makes plenty of sense.

If you want to make an issue about that, feel free. But we shouldn't hide empty computed fields.
