### ISSUE TITLE
Add a description field to radio field type

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/ideas#954]
Hi, 

I'd like to replicate this Tailwind radio layout:
<img width="384" alt="Screenshot 2023-02-27 at 18 04 04" src="https://user-images.githubusercontent.com/72254741/221660391-0cf06089-8e33-4cec-a5b6-ac4345b4fbe8.png">

It'd be helpful if there was a way to add an optional description to each key in the options array.

**Comment by aerni** [comment]
I don't think adding an optional description to the fieldtype is a good idea. It would work in your simple example, but you might have more complicated layouts with more data than a simple description that wouldn't work that way:

<img width="811" alt="CleanShot 2023-03-15 at 10 04 06@2x" src="https://user-images.githubusercontent.com/23167701/225332971-a2e405b0-288b-4190-963f-3d6ae3f4bae1.png">

I think the best way to go about this issue is to create a collection or global with the data you need and render that dynamically in your template. That's how I do it.

**Comment by stephenmeehanuk** [comment]
Thanks for the suggestion. I think for my problem, I might be able to get away with making the description part of the view template. If poss, I'd like to try and keep everything in forms.
